name: Workflow Validation

on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'

jobs:
  validate-workflows:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Validate workflow syntax
      run: |
        echo "Validating GitHub Actions workflow files..."
        
        # Check for common issues
        echo "Checking for deprecated actions..."
        if grep -r "actions/upload-artifact@v[123]" .github/workflows/; then
          echo "ERROR: Found deprecated upload-artifact action. Please use v4 or later."
          exit 1
        fi
        
        if grep -r "actions/download-artifact@v[123]" .github/workflows/; then
          echo "ERROR: Found deprecated download-artifact action. Please use v4 or later."
          exit 1
        fi
        
        if grep -r "actions/cache@v[12]" .github/workflows/; then
          echo "WARNING: Found old cache action. Consider upgrading to v4."
        fi
        
        # Check for Windows builds (since app only supports Linux/macOS)
        if grep -r "GOOS=windows\|windows-" .github/workflows/; then
          echo "WARNING: Found Windows builds. Application currently only supports Linux and macOS."
        fi
        
        echo "Workflow validation passed!"
    
    - name: Check workflow files are valid YAML
      run: |
        echo "Validating YAML syntax..."
        for file in .github/workflows/*.yml .github/workflows/*.yaml; do
          if [ -f "$file" ]; then
            echo "Checking $file..."
            python3 -c "import yaml; yaml.safe_load(open('$file'))"
            echo "✅ $file is valid YAML"
          fi
        done
    
    - name: Lint workflow files
      uses: rhysd/actionlint-action@v1
      with:
        fail-on-error: true
